name: Run checks in main and release

on:
  pull_request:
    branches:
      - '*release*'
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        fetch-depth: 0
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "16.x"
    - name: Check package-lock.json
      id: check-package-lock
      run: |
        npm install
        if [[ `git status --porcelain package-lock.json` ]]; then
          echo "Changes detected in package-lock.json"
          echo "changes_detected=true" >> $GITHUB_OUTPUT
          if [[ "${GITHUB_HEAD_REF}" == "dev" || "${GITHUB_HEAD_REF}" == "main" ]]; then
            echo "Error: package-lock.json is outdated but cannot auto-commit to ${GITHUB_HEAD_REF}. Please review and commit the changes."
            git diff
            exit 1
          fi
        else
          echo "No changes in package-lock.json"
          echo "changes_detected=false" >> $GITHUB_OUTPUT
        fi
    - name: Commit and push package-lock.json
      if: steps.check-package-lock.outputs.changes_detected == 'true'
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        message: "ci: update package-lock.json [skip actions]"
        add: package-lock.json
    - name: Install dependencies (clean install)
      run: npm ci
    - name: Check build
      run: npm run build
    - name: Run linter checks
      run: npm run lint
    - name: Run tests and coverage
      run: npm run test:coverage
