name: Tag
on:
  push:
    branches:
      - main
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ env.DEFAULT_BRANCH }}
        fetch-depth: 0
        token: ${{ secrets.SERVICE_TOKEN }}
    - name: Get version from package.json
      run: |
        version=$(sed -n '3p' package.json | sed 's/.*"version": "\(.*\)".*/\1/')
        echo "VERSION=$version" >> "$GITHUB_ENV"
    - name: Create git tag
      run: |
        git tag "v${{ env.VERSION }}"
    - name: Push git tag
      run: git push origin "v${{ env.VERSION }}"
